apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: argocd-repo-server
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/component: repo-server
  name: argocd-repo-server
  namespace: argocd
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-repo-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: argocd-repo-server
    spec:
      automountServiceAccountToken: false
      imagePullSecrets:
        - name: SecretInSameNamespace
        - name: SecretInAnotherNamespace
      containers:
        - name: argocd-repo-server
          image: quay.io/argoproj/argocd:latest
          imagePullPolicy: Always
          command:
            - entrypoint.sh
            - argocd-repo-server
            - --redis
            - $(ARGOCD_REDIS_SERVICE):6379
          ports:
            - containerPort: 8081
            - containerPort: 8084


