apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patchesJson6902:
  - target:
      version: v1
      group: ""
      kind: ConfigMap
      name: argocd-redis-ha-health-configmap
      namespace: argocd
    path: overlays/remove-namespace.yaml
  - target:
      version: v1
      group: ""
      kind: ConfigMap
      name: argocd-redis-ha-configmap
      namespace: argocd
    path: overlays/remove-namespace.yaml

